"""initial schema

Revision ID: 7bbe0f1f6325
Revises: 
Create Date: 2026-09-30 23:36:49.086120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbe0f1f6325'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('incident_type', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Double(), nullable=False),
    sa.Column('affected_services', sa.JSON(), nullable=False),
    sa.Column('anomalies_detected', sa.Integer(), nullable=False),
    sa.Column('primary_metric_impacted', sa.String(length=64), nullable=False),
    sa.Column('mttd_seconds', sa.Double(), nullable=False),
    sa.Column('mttr_seconds', sa.Double(), nullable=True),
    sa.Column('root_cause_service', sa.String(length=128), nullable=False),
    sa.Column('remediation_action_taken', sa.String(length=256), nullable=False),
    sa.Column('lifecycle_timeline', sa.JSON(), nullable=False),
    sa.Column('operator_comments', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_data', 'incidents', ['start_time', 'status'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=256), nullable=True),
    sa.Column('exception_type', sa.String(length=128), nullable=True),
    sa.Column('duration_ms', sa.Double(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_data', 'log_entries', ['timestamp', 'service_id', 'level', 'request_id', 'trace_id'], unique=False)
    op.create_table('telemetry_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('cpu_percent', sa.Double(), nullable=False),
    sa.Column('memory_mb', sa.Double(), nullable=False),
    sa.Column('request_rate', sa.Double(), nullable=False),
    sa.Column('latency_p95_ms', sa.Double(), nullable=False),
    sa.Column('error_rate_percent', sa.Double(), nullable=False),
    sa.Column('db_query_latency_ms', sa.Double(), nullable=False),
    sa.Column('db_connections', sa.Integer(), nullable=False),
    sa.Column('queue_backlog', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_data', 'telemetry_metrics', ['timestamp', 'service_id'], unique=False)
    op.create_table('anomaly_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('isolation_forest_score', sa.Double(), nullable=False),
    sa.Column('autoencoder_recon_error', sa.Double(), nullable=False),
    sa.Column('context_score', sa.Double(), nullable=False),
    sa.Column('final_anomaly_score', sa.Double(), nullable=False),
    sa.Column('threshold', sa.Double(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_anomalyEvent_Incident', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomaly_data', 'anomaly_events', ['detected_at', 'service_id', 'final_anomaly_score'], unique=False)
    op.create_table('rca_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_service_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_service_name', sa.String(length=128), nullable=False),
    sa.Column('candidate_type', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('metric_evidence_score', sa.Double(), nullable=False),
    sa.Column('dependency_impact_score', sa.Double(), nullable=False),
    sa.Column('temporal_precedence_score', sa.Double(), nullable=False),
    sa.Column('log_evidence_score', sa.Double(), nullable=False),
    sa.Column('fault_signature_score', sa.Double(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('evidence_items', sa.JSON(), nullable=False),
    sa.Column('fault_signature_matched', sa.String(length=256), nullable=True),
    sa.Column('lead_lag_relationship', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_rcaResult_incident'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_audits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('recommendation_id', sa.String(length=64), nullable=False),
    sa.Column('playbook_id', sa.String(length=64), nullable=False),
    sa.Column('action_title', sa.String(length=256), nullable=False),
    sa.Column('target_service', sa.String(length=128), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('approver', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_status', sa.String(length=64), nullable=False),
    sa.Column('execution_logs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_remediationAudit_incident'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_remediationAudit_data', 'remediation_audits', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_remediationAudit_data', table_name='remediation_audits')
    op.drop_table('remediation_audits')
    op.drop_table('rca_results')
    op.drop_index('ix_anomaly_data', table_name='anomaly_events')
    op.drop_table('anomaly_events')
    op.drop_index('ix_metric_data', table_name='telemetry_metrics')
    op.drop_table('telemetry_metrics')
    op.drop_index('ix_log_data', table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index('ix_incident_data', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
